### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by postoroniy** [SpinalHDL/SpinalDoc#23]
I've tried sbt way, it was OK.
now tried makefile and got error
 make run
scalac -cp "./build/scala:./lib/spinalhdl-core_2.11-0.10.2.jar:./lib/spinalhdl-lib_2.11-0.10.2.jar:./lib/scopt_2.11-3.4.0.jar" -d build/scala scala/Main.scala
error: error while loading package, class file needed by package is missing.
reference value macros of package reflect refers to nonexisting symbol.
error: error while loading VecFactory, class file needed by VecFactory is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading UIntCast, class file needed by UIntCast is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading SIntCast, class file needed by SIntCast is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading BitsCast, class file needed by BitsCast is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading SFixCast, class file needed by SFixCast is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading UFixCast, class file needed by UFixCast is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading Data, class file needed by Data is missing.
reference value <init>$default$2 of object deprecated refers to nonexisting symbol.
error: error while loading DataPrimitives, class file needed by DataPrimitives is missing.
reference value <init>$default$2 of object deprecated refers to nonexisting symbol.
error: error while loading Mem, class file needed by Mem is missing.
reference value <init>$default$1 of object deprecated refers to nonexisting symbol.
error: error while loading DataCarrier, class file needed by DataCarrier is missing.
reference value <init>$default$2 of object deprecated refers to nonexisting symbol.
scala/Main.scala:6: error: class file needed by package is missing.
reference type StringContext of package scala refers to nonexisting symbol.
    val a,b = in UInt(4 bits)
                        ^
scala/Main.scala:7: error: class file needed by package is missing.
reference type StringContext of package scala refers to nonexisting symbol.
    val result = out UInt(4 bits)
                            ^
13 errors found
make: *** [compile] Error 1

**Comment by Dolu1990** [comment]
Hmm it is strange, and you get this error without editing anything right ? Because on my computer it work without issue.
Then which scala version are you using ?  (scala -version)
It should be 2.11.x . Depending the Linux distribution and version, i already have seen people getting the 2.10.x from packet manager (which will not work).

**Comment by postoroniy** [comment]
You are right. I've not edited just followed and checked sbt and makefile ways only

> scala -version
> Scala code runner version 2.9.2 -- Copyright 2002-2011, LAMP/EPFL

looks wrong then.
it seems that SBT way is better.
I think it's ok to support just one way road :)(SBT)

**Comment by postoroniy** [comment]
well tried "new" scala and got this error in makefile way:
```
make run
scalac -cp "./build/scala:./lib/spinalhdl-core_2.11-0.10.2.jar:./lib/spinalhdl-lib_2.11-0.10.2.jar:./lib/scopt_2.11-3.4.0.jar" -d build/scala scala/Main.scala
scala  -cp "./build/scala:./lib/spinalhdl-core_2.11-0.10.2.jar:./lib/spinalhdl-lib_2.11-0.10.2.jar:./lib/scopt_2.11-3.4.0.jar" Main
[Runtime] SpinalHDL 0.10.2
[Runtime] JVM max memory : 227.5MiB
[Runtime] Current date : 2017.01.03 22:17:10
[Progress] at 0.000 : Start elaboration

**********************************************************************************************
[Warning] Elaboration failed (0 error).
          Spinal will restart with scala trace to help you to find the problem.
**********************************************************************************************

[Progress] at 0.333 : Start elaboration
java.lang.UnsupportedClassVersionError: spinal/core/dontName
	at spinal.core.AnnotationUtils$.isDontName(Misc.scala:422)
	at spinal.core.Misc$$anonfun$5.apply(Misc.scala:119)
	at spinal.core.Misc$$anonfun$5.apply(Misc.scala:119)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
	at spinal.core.Misc$.explore$1(Misc.scala:119)
	at spinal.core.Misc$.reflect(Misc.scala:106)
	at spinal.core.Component.nameElements(Component.scala:142)
	at spinal.core.Component.delayedInit(Component.scala:50)
	at TopLevel.<init>(Main.scala:4)
	at Main$$anonfun$main$1.apply(Main.scala:14)
	at Main$$anonfun$main$1.apply(Main.scala:14)
	at spinal.core.PhaseCreateComponent.impl(Phase.scala:1536)
	at spinal.core.PhaseContext.doPhase(Phase.scala:175)
	at spinal.core.SpinalVhdlBoot$$anonfun$singleShot$23.apply(Phase.scala:1663)
	at spinal.core.SpinalVhdlBoot$$anonfun$singleShot$23.apply(Phase.scala:1662)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at spinal.core.SpinalVhdlBoot$.singleShot(Phase.scala:1662)
	at spinal.core.SpinalVhdlBoot$.apply(Phase.scala:1564)
	at spinal.core.Spinal$.apply(Spinal.scala:164)
	at spinal.core.SpinalConfig.generate(Spinal.scala:89)
	at spinal.core.SpinalVhdl$.apply(Spinal.scala:181)
	at Main$.main(Main.scala:14)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
make: *** [run] Error 1
scala -version
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
```

**Comment by Dolu1990** [comment]
Hoooo yes !
I remember about this one, so basicaly, that was because the SpinalHDL 0.10.2 was released by an JVM 8 without the JVM 7 compatibilty.
Recent releases of SpinalHDL are fine with JVM 7 or 8, i updated the git one hour before to use the SpinalHDL 0.10.7 which is allright with JVM 7, you just need to git pull ^^
Sorry for it.

**Comment by postoroniy** [comment]
Thanks, all good now

**Comment by Dolu1990** [comment]
Great ^^
Thanks aswell !
